# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160403_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeTemplate',
            fields=[
                ('dept', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=200)),
                ('IC', models.IntegerField(default=0)),
                ('DC', models.IntegerField(default=0)),
                ('UGP1', models.IntegerField(default=0)),
                ('UGP2', models.IntegerField(default=0)),
                ('DE', models.IntegerField(default=0)),
                ('OE', models.IntegerField(default=0)),
                ('SO', models.IntegerField(default=0)),
                ('HSS1', models.IntegerField(default=0)),
                ('HSS2', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
    ]
